const tileObjArr = [
    {
        name: 'empty',
        type: 'empty',
        tileValue: 0,
        adjecentTilesHorizontal: [0, 1, 7, 3],
        adjecentTilesVertical: [0, 1, 2, 5],
    },
    {
        name: 'topleftcorner',
        type: 'grass',
        tileValue: 1,
        adjecentTilesHorizontal: [5, 2, 12, 10],
        adjecentTilesVertical: [7, 3, 10],
        tileImagePath: 'assets/tiles/grass/topleftcorner.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'toprightcorner',
        type: 'grass',
        tileValue: 2,
        adjecentTilesHorizontal: [0, 1, 5],
        adjecentTilesVertical: [8, 11, 4],
        tileImagePath: 'assets/tiles/grass/toprightcorner.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'bottomleftcorner',
        type: 'grass',
        tileValue: 3,
        adjecentTilesHorizontal: [4, 6, 12],
        adjecentTilesVertical: [0],
        tileImagePath: 'assets/tiles/grass/bottomleftcorner.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'bottomrightcorner',
        type: 'grass',
        tileValue: 4,
        adjecentTilesHorizontal: [0, 3, 8],
        adjecentTilesVertical: [0, 2],
        tileImagePath: 'assets/tiles/grass/bottomrightcorner.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'topflat',
        type: 'grass',
        tileValue: 5,
        adjecentTilesHorizontal: [5, 2, 10],
        adjecentTilesVertical: [9, 6],
        tileImagePath: 'assets/tiles/grass/topflat.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'bottomflat',
        type: 'grass',
        tileValue: 6,
        adjecentTilesHorizontal: [6, 4, 12],
        adjecentTilesVertical: [0],
        tileImagePath: 'assets/tiles/grass/bottomflat.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'leftflat',
        type: 'grass',
        tileValue: 7,
        adjecentTilesHorizontal: [9, 8, 11],
        adjecentTilesVertical: [7, 3, 10],
        tileImagePath: 'assets/tiles/grass/leftflat.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'rightflat',
        type: 'grass',
        tileValue: 8,
        adjecentTilesHorizontal: [0],
        adjecentTilesVertical: [8, 4, 11],
        tileImagePath: 'assets/tiles/grass/rightflat.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'middle',
        type: 'grass',
        tileValue: 9,
        adjecentTilesHorizontal: [9, 8, 11, 13],
        adjecentTilesVertical: [9, 6, 12, 13],
        tileImagePath: 'assets/tiles/grass/middle.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'topleftinvertedcorner',
        type: 'grass',
        tileValue: 10,
        adjecentTilesHorizontal: [9, 8, 11, 13],
        adjecentTilesVertical: [9, 6, 12, 13],
        tileImagePath: 'assets/tiles/grass/topleftinvertedcorner.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'toprightinvertedcorner',
        type: 'grass',
        tileValue: 11,
        adjecentTilesHorizontal: [2, 5, 10],
        adjecentTilesVertical: [9, 6, 12, 13],
        tileImagePath: 'assets/tiles/grass/toprightinvertedcorner.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'bottomleftinvertedcorner',
        type: 'grass',
        tileValue: 12,
        adjecentTilesHorizontal: [6, 9, 8, 13, 11],
        adjecentTilesVertical: [7, 3, 10],
        tileImagePath: 'assets/tiles/grass/bottomleftinvertedcorner.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'bottomrightinvertedcorner',
        type: 'grass',
        tileValue: 13,
        adjecentTilesHorizontal: [4, 6, 12],
        adjecentTilesVertical: [4, 8, 11],
        tileImagePath: 'assets/tiles/grass/bottomrightinvertedcorner.png',
        toughness: 2,
        hardness: 0,
    }
]