const tileObjArr = [
    {
        name: 'topleftcorner',
        type: 'grass',
        tileValue: 1,
        adjecentTilesHorizontal: [5, 2],
        adjecentTilesVertical: [3, 7],
        tileImagePath: 'assets/tiles/grass/topleftcorner.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'toprightcorner',
        type: 'grass',
        tileValue: 2,
        adjecentTilesHorizontal: [0],
        adjecentTilesVertical: [4, 8],
        tileImagePath: 'assets/tiles/grass/toprightcorner.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'bottomleftcorner',
        type: 'grass',
        tileValue: 3,
        adjecentTilesHorizontal: [4, 6],
        adjecentTilesVertical: [0],
        tileImagePath: 'assets/tiles/grass/bottomleftcorner.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'bottomrightcorner',
        type: 'grass',
        tileValue: 4,
        adjecentTilesHorizontal: [0],
        adjecentTilesVertical: [0],
        tileImagePath: 'assets/tiles/grass/bottomrightcorner.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'topflat',
        type: 'grass',
        tileValue: 5,
        adjecentTilesHorizontal: [5, 2],
        adjecentTilesVertical: [6, 9],
        tileImagePath: 'assets/tiles/grass/topflat.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'bottomflat',
        type: 'grass',
        tileValue: 6,
        adjecentTilesHorizontal: [6, 4],
        adjecentTilesVertical: [0],
        tileImagePath: 'assets/tiles/grass/bottomflat.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'leftflat',
        type: 'grass',
        tileValue: 7,
        adjecentTilesHorizontal: [8, 9],
        adjecentTilesVertical: [7, 3],
        tileImagePath: 'assets/tiles/grass/leftflat.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'rightflat',
        type: 'grass',
        tileValue: 8,
        adjecentTilesHorizontal: [0],
        adjecentTilesVertical: [8, 4],
        tileImagePath: 'assets/tiles/grass/rightflat.png',
        toughness: 2,
        hardness: 0,
    },
    {
        name: 'middle',
        type: 'grass',
        tileValue: 9,
        adjecentTilesHorizontal: [9, 8],
        adjecentTilesVertical: [5, 9],
        tileImagePath: 'assets/tiles/grass/middle.png',
        toughness: 2,
        hardness: 0,
    }
]